language: c

sudo: required
dist: trusty

sources:
  - ubuntu-toolchain-r-test
  - llvm-toolchain-precise-3.6

os:
  - linux

before_install:
  - sudo apt-get install gfortran libblas-dev liblapack-dev
  - sudo apt-get install cmake python gcc cmake-data g++
  - cd; git clone https://github.com/lanl/qmd-progress.git
  - cd; git clone https://github.com/lanl/bml.git

  # Install BML, PROGRESS and LAMMPS
  - cd bml; CC=gcc FC=gfortran CMAKE_BUILD_TYPE=Release BLAS_VENDOR=GNU BML_OPENMP=yes BML_TESTING=no ./build.sh configure
  - cd build; make; make install; cd
  - cd qmd-progress; CC=gcc FC=gfortran PROGRESS_MPI=no PROGRESS_TESTING=yes BLAS_VENDOR=GNU PKG_CONFIG_PATH=~/bml/install/lib/pkgconfig PROGRESS_OPENMP=yes ./build.sh configure
  - cd build; make; make install; cd 
  
before_script:
  - cd ~/build/lanl/LATTE/

env:
  - CMAKE_BUILD_TYPE=Release FC=gfortran CC=gcc CXX=g++ CHOICES=gfort.lapack
  - CMAKE_BUILD_TYPE=Release FC=gfortran CC=gcc CXX=g++ CVR=ON CHOICES=gfort.lapack.progress

script:
  -  cp -f -v ./makefiles/makefile.CHOICES.${CHOICES} makefile.CHOICES
  -  make; make test

after_success:
  - echo "success"
  - make cov
  - bash <(curl -s https://codecov.io/bash)
